tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
# tap "sambadevi/powerlevel9k"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Modern replacement for 'ls'
brew "exa"
# Perl lib for reading and writing EXIF metadata
brew "exiftool"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# brew "jenv"
brew "mas"
# brew "nvm"
# brew "yarn"
# brew "zsh-syntax-highlighting"
# brew "sambadevi/powerlevel9k/powerlevel9k"
# cask "adoptopenjdk11"
# cask "adoptopenjdk16"
# cask "adoptopenjdk8"
cask "alfred"
cask "brave-browser"
git cask "docker"
cask "dropbox"
# cask "google-chrome"
# cask "iterm2"
# cask "jetbrains-toolbox"
cask "postman"
# cask "slack"
# cask "spectacle" - replace with "rectangle"
cask "spotify"
cask "visual-studio-code"
cask "zoom"
# cask "1password"
