tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
tap "homebrew/services"
# tap "sambadevi/powerlevel9k"
brew "asdf"
brew "bat"
brew "exa"
brew "exiftool"
# brew "gh"
brew "httpie"
brew "less"
brew "mas"
# brew "zsh-syntax-highlighting"
# brew "sambadevi/powerlevel9k/powerlevel9k"
cask "alfred"
cask "brave-browser"
cask "docker"
cask "dropbox"
# cask "google-chrome"
# cask "iterm2"
# cask "jetbrains-toolbox"
# cask "keyboard-maestro"
# cask "philips-hue-sync"
cask "postman"
# cask "rectangle"
cask "spotify"
cask "visual-studio-code"
cask "zoom"
# cask "1password"
mas "Bear", id: 1091189122
